services:
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
      network: host
    network_mode: host
    volumes:
      - ./server:/app
      - /app/__pycache__
    environment:
      - PYTHONUNBUFFERED=1
    env_file:
      - ./server/.env

  frontend:
    build:
      context: ./admin/my-dashboard
      dockerfile: Dockerfile
      network: host
    network_mode: host
    volumes:
      - ./admin/my-dashboard:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - VITE_API_URL=http://localhost:8000
    depends_on:
      - backend
